export const ONBOARDING_TITLES = [
  { tmdbId: 278, title: 'The Shawshank Redemption' },
  { tmdbId: 155, title: 'The Dark Knight' },
  { tmdbId: 129, title: 'Spirited Away' },
  { tmdbId: 680, title: 'Pulp Fiction' },
  { tmdbId: 597, title: 'Titanic' },
  { tmdbId: 419430, title: 'Get Out' },
  { tmdbId: 157336, title: 'Interstellar' },
  { tmdbId: 194, title: 'Amelie' },
  { tmdbId: 76341, title: 'Mad Max: Fury Road' },
  { tmdbId: 238, title: 'The Godfather' },
  { tmdbId: 496243, title: 'Parasite' },
  { tmdbId: 346698, title: 'Barbie' },
  { tmdbId: 27205, title: 'Inception' },
  { tmdbId: 603, title: 'The Matrix' },
  { tmdbId: 769, title: 'GoodFellas' },
  { tmdbId: 37799, title: 'The Social Network' },
  { tmdbId: 545611, title: 'Everything Everywhere All at Once' },
  { tmdbId: 1417, title: "Pan's Labyrinth" },
  { tmdbId: 120467, title: 'The Grand Budapest Hotel' },
  { tmdbId: 329, title: 'Jurassic Park' },
  { tmdbId: 274, title: 'The Silence of the Lambs' },
  { tmdbId: 550, title: 'Fight Club' },
  { tmdbId: 120, title: 'The Lord of the Rings: The Fellowship of the Ring' },
  { tmdbId: 284054, title: 'Black Panther' },
] as const;

